/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nikhilesh.liferay.algorithm.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ALGTree service. Represents a row in the &quot;FOO_ALGTree&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nikhilesh.liferay.algorithm.model.impl.ALGTreeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nikhilesh.liferay.algorithm.model.impl.ALGTreeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ALGTree
 * @see com.nikhilesh.liferay.algorithm.model.impl.ALGTreeImpl
 * @see com.nikhilesh.liferay.algorithm.model.impl.ALGTreeModelImpl
 * @generated
 */
@ProviderType
public interface ALGTreeModel extends BaseModel<ALGTree>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a alg tree model instance should use the {@link ALGTree} interface instead.
	 */

	/**
	 * Returns the primary key of this alg tree.
	 *
	 * @return the primary key of this alg tree
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this alg tree.
	 *
	 * @param primaryKey the primary key of this alg tree
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this alg tree.
	 *
	 * @return the uuid of this alg tree
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this alg tree.
	 *
	 * @param uuid the uuid of this alg tree
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the tree ID of this alg tree.
	 *
	 * @return the tree ID of this alg tree
	 */
	public long getTreeId();

	/**
	 * Sets the tree ID of this alg tree.
	 *
	 * @param treeId the tree ID of this alg tree
	 */
	public void setTreeId(long treeId);

	/**
	 * Returns the group ID of this alg tree.
	 *
	 * @return the group ID of this alg tree
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this alg tree.
	 *
	 * @param groupId the group ID of this alg tree
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this alg tree.
	 *
	 * @return the company ID of this alg tree
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this alg tree.
	 *
	 * @param companyId the company ID of this alg tree
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this alg tree.
	 *
	 * @return the user ID of this alg tree
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this alg tree.
	 *
	 * @param userId the user ID of this alg tree
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this alg tree.
	 *
	 * @return the user uuid of this alg tree
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this alg tree.
	 *
	 * @param userUuid the user uuid of this alg tree
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this alg tree.
	 *
	 * @return the user name of this alg tree
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this alg tree.
	 *
	 * @param userName the user name of this alg tree
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this alg tree.
	 *
	 * @return the create date of this alg tree
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this alg tree.
	 *
	 * @param createDate the create date of this alg tree
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this alg tree.
	 *
	 * @return the modified date of this alg tree
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this alg tree.
	 *
	 * @param modifiedDate the modified date of this alg tree
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this alg tree.
	 *
	 * @return the status of this alg tree
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this alg tree.
	 *
	 * @param status the status of this alg tree
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this alg tree.
	 *
	 * @return the status by user ID of this alg tree
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this alg tree.
	 *
	 * @param statusByUserId the status by user ID of this alg tree
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this alg tree.
	 *
	 * @return the status by user uuid of this alg tree
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this alg tree.
	 *
	 * @param statusByUserUuid the status by user uuid of this alg tree
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this alg tree.
	 *
	 * @return the status by user name of this alg tree
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this alg tree.
	 *
	 * @param statusByUserName the status by user name of this alg tree
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this alg tree.
	 *
	 * @return the status date of this alg tree
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this alg tree.
	 *
	 * @param statusDate the status date of this alg tree
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this alg tree.
	 *
	 * @return the name of this alg tree
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this alg tree.
	 *
	 * @param name the name of this alg tree
	 */
	public void setName(String name);

	/**
	 * Returns the description of this alg tree.
	 *
	 * @return the description of this alg tree
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this alg tree.
	 *
	 * @param description the description of this alg tree
	 */
	public void setDescription(String description);

	/**
	 * Returns <code>true</code> if this alg tree is approved.
	 *
	 * @return <code>true</code> if this alg tree is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this alg tree is denied.
	 *
	 * @return <code>true</code> if this alg tree is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this alg tree is a draft.
	 *
	 * @return <code>true</code> if this alg tree is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this alg tree is expired.
	 *
	 * @return <code>true</code> if this alg tree is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this alg tree is inactive.
	 *
	 * @return <code>true</code> if this alg tree is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this alg tree is incomplete.
	 *
	 * @return <code>true</code> if this alg tree is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this alg tree is pending.
	 *
	 * @return <code>true</code> if this alg tree is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this alg tree is scheduled.
	 *
	 * @return <code>true</code> if this alg tree is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ALGTree algTree);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ALGTree> toCacheModel();

	@Override
	public ALGTree toEscapedModel();

	@Override
	public ALGTree toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}