/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nikhilesh.liferay.algorithm.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TreeNode service. Represents a row in the &quot;FOO_TreeNode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nikhilesh.liferay.algorithm.model.impl.TreeNodeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nikhilesh.liferay.algorithm.model.impl.TreeNodeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreeNode
 * @see com.nikhilesh.liferay.algorithm.model.impl.TreeNodeImpl
 * @see com.nikhilesh.liferay.algorithm.model.impl.TreeNodeModelImpl
 * @generated
 */
@ProviderType
public interface TreeNodeModel extends BaseModel<TreeNode>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tree node model instance should use the {@link TreeNode} interface instead.
	 */

	/**
	 * Returns the primary key of this tree node.
	 *
	 * @return the primary key of this tree node
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tree node.
	 *
	 * @param primaryKey the primary key of this tree node
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tree node.
	 *
	 * @return the uuid of this tree node
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this tree node.
	 *
	 * @param uuid the uuid of this tree node
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the tree node ID of this tree node.
	 *
	 * @return the tree node ID of this tree node
	 */
	public long getTreeNodeId();

	/**
	 * Sets the tree node ID of this tree node.
	 *
	 * @param treeNodeId the tree node ID of this tree node
	 */
	public void setTreeNodeId(long treeNodeId);

	/**
	 * Returns the group ID of this tree node.
	 *
	 * @return the group ID of this tree node
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tree node.
	 *
	 * @param groupId the group ID of this tree node
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tree node.
	 *
	 * @return the company ID of this tree node
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tree node.
	 *
	 * @param companyId the company ID of this tree node
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tree node.
	 *
	 * @return the user ID of this tree node
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tree node.
	 *
	 * @param userId the user ID of this tree node
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tree node.
	 *
	 * @return the user uuid of this tree node
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tree node.
	 *
	 * @param userUuid the user uuid of this tree node
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tree node.
	 *
	 * @return the user name of this tree node
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tree node.
	 *
	 * @param userName the user name of this tree node
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tree node.
	 *
	 * @return the create date of this tree node
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tree node.
	 *
	 * @param createDate the create date of this tree node
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tree node.
	 *
	 * @return the modified date of this tree node
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tree node.
	 *
	 * @param modifiedDate the modified date of this tree node
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the value of this tree node.
	 *
	 * @return the value of this tree node
	 */
	public int getValue();

	/**
	 * Sets the value of this tree node.
	 *
	 * @param value the value of this tree node
	 */
	public void setValue(int value);

	/**
	 * Returns the level of this tree node.
	 *
	 * @return the level of this tree node
	 */
	public int getLevel();

	/**
	 * Sets the level of this tree node.
	 *
	 * @param level the level of this tree node
	 */
	public void setLevel(int level);

	/**
	 * Returns the parent ID of this tree node.
	 *
	 * @return the parent ID of this tree node
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this tree node.
	 *
	 * @param parentId the parent ID of this tree node
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the tree ID of this tree node.
	 *
	 * @return the tree ID of this tree node
	 */
	public long getTreeId();

	/**
	 * Sets the tree ID of this tree node.
	 *
	 * @param treeId the tree ID of this tree node
	 */
	public void setTreeId(long treeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TreeNode treeNode);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TreeNode> toCacheModel();

	@Override
	public TreeNode toEscapedModel();

	@Override
	public TreeNode toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}