/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nikhilesh.liferay.algorithm.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.nikhilesh.liferay.algorithm.model.TreeNode;
import com.nikhilesh.liferay.algorithm.model.TreeNodeModel;
import com.nikhilesh.liferay.algorithm.model.TreeNodeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TreeNode service. Represents a row in the &quot;FOO_TreeNode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TreeNodeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TreeNodeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TreeNodeImpl
 * @see TreeNode
 * @see TreeNodeModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TreeNodeModelImpl extends BaseModelImpl<TreeNode>
	implements TreeNodeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tree node model instance should use the {@link TreeNode} interface instead.
	 */
	public static final String TABLE_NAME = "FOO_TreeNode";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "treeNodeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "value", Types.INTEGER },
			{ "level", Types.INTEGER },
			{ "parentId", Types.BIGINT },
			{ "treeId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("treeNodeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("value", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("level", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("treeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FOO_TreeNode (uuid_ VARCHAR(75) null,treeNodeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,value INTEGER,level INTEGER,parentId LONG,treeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table FOO_TreeNode";
	public static final String ORDER_BY_JPQL = " ORDER BY treeNode.treeNodeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FOO_TreeNode.treeNodeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.nikhilesh.liferay.algorithm.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.nikhilesh.liferay.algorithm.model.TreeNode"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.nikhilesh.liferay.algorithm.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.nikhilesh.liferay.algorithm.model.TreeNode"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.nikhilesh.liferay.algorithm.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.nikhilesh.liferay.algorithm.model.TreeNode"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LEVEL_COLUMN_BITMASK = 4L;
	public static final long TREEID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long TREENODEID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TreeNode toModel(TreeNodeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TreeNode model = new TreeNodeImpl();

		model.setUuid(soapModel.getUuid());
		model.setTreeNodeId(soapModel.getTreeNodeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setValue(soapModel.getValue());
		model.setLevel(soapModel.getLevel());
		model.setParentId(soapModel.getParentId());
		model.setTreeId(soapModel.getTreeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TreeNode> toModels(TreeNodeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TreeNode> models = new ArrayList<TreeNode>(soapModels.length);

		for (TreeNodeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.nikhilesh.liferay.algorithm.service.util.ServiceProps.get(
				"lock.expiration.time.com.nikhilesh.liferay.algorithm.model.TreeNode"));

	public TreeNodeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _treeNodeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTreeNodeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _treeNodeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TreeNode.class;
	}

	@Override
	public String getModelClassName() {
		return TreeNode.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("treeNodeId", getTreeNodeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("value", getValue());
		attributes.put("level", getLevel());
		attributes.put("parentId", getParentId());
		attributes.put("treeId", getTreeId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long treeNodeId = (Long)attributes.get("treeNodeId");

		if (treeNodeId != null) {
			setTreeNodeId(treeNodeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer value = (Integer)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		Integer level = (Integer)attributes.get("level");

		if (level != null) {
			setLevel(level);
		}

		Long parentId = (Long)attributes.get("parentId");

		if (parentId != null) {
			setParentId(parentId);
		}

		Long treeId = (Long)attributes.get("treeId");

		if (treeId != null) {
			setTreeId(treeId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTreeNodeId() {
		return _treeNodeId;
	}

	@Override
	public void setTreeNodeId(long treeNodeId) {
		_treeNodeId = treeNodeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getValue() {
		return _value;
	}

	@Override
	public void setValue(int value) {
		_value = value;
	}

	@JSON
	@Override
	public int getLevel() {
		return _level;
	}

	@Override
	public void setLevel(int level) {
		_columnBitmask |= LEVEL_COLUMN_BITMASK;

		if (!_setOriginalLevel) {
			_setOriginalLevel = true;

			_originalLevel = _level;
		}

		_level = level;
	}

	public int getOriginalLevel() {
		return _originalLevel;
	}

	@JSON
	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		_parentId = parentId;
	}

	@JSON
	@Override
	public long getTreeId() {
		return _treeId;
	}

	@Override
	public void setTreeId(long treeId) {
		_columnBitmask |= TREEID_COLUMN_BITMASK;

		if (!_setOriginalTreeId) {
			_setOriginalTreeId = true;

			_originalTreeId = _treeId;
		}

		_treeId = treeId;
	}

	public long getOriginalTreeId() {
		return _originalTreeId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				TreeNode.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TreeNode.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TreeNode toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TreeNode)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TreeNodeImpl treeNodeImpl = new TreeNodeImpl();

		treeNodeImpl.setUuid(getUuid());
		treeNodeImpl.setTreeNodeId(getTreeNodeId());
		treeNodeImpl.setGroupId(getGroupId());
		treeNodeImpl.setCompanyId(getCompanyId());
		treeNodeImpl.setUserId(getUserId());
		treeNodeImpl.setUserName(getUserName());
		treeNodeImpl.setCreateDate(getCreateDate());
		treeNodeImpl.setModifiedDate(getModifiedDate());
		treeNodeImpl.setValue(getValue());
		treeNodeImpl.setLevel(getLevel());
		treeNodeImpl.setParentId(getParentId());
		treeNodeImpl.setTreeId(getTreeId());

		treeNodeImpl.resetOriginalValues();

		return treeNodeImpl;
	}

	@Override
	public int compareTo(TreeNode treeNode) {
		long primaryKey = treeNode.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TreeNode)) {
			return false;
		}

		TreeNode treeNode = (TreeNode)obj;

		long primaryKey = treeNode.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TreeNodeModelImpl treeNodeModelImpl = this;

		treeNodeModelImpl._originalUuid = treeNodeModelImpl._uuid;

		treeNodeModelImpl._originalGroupId = treeNodeModelImpl._groupId;

		treeNodeModelImpl._setOriginalGroupId = false;

		treeNodeModelImpl._originalCompanyId = treeNodeModelImpl._companyId;

		treeNodeModelImpl._setOriginalCompanyId = false;

		treeNodeModelImpl._setModifiedDate = false;

		treeNodeModelImpl._originalLevel = treeNodeModelImpl._level;

		treeNodeModelImpl._setOriginalLevel = false;

		treeNodeModelImpl._originalTreeId = treeNodeModelImpl._treeId;

		treeNodeModelImpl._setOriginalTreeId = false;

		treeNodeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TreeNode> toCacheModel() {
		TreeNodeCacheModel treeNodeCacheModel = new TreeNodeCacheModel();

		treeNodeCacheModel.uuid = getUuid();

		String uuid = treeNodeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			treeNodeCacheModel.uuid = null;
		}

		treeNodeCacheModel.treeNodeId = getTreeNodeId();

		treeNodeCacheModel.groupId = getGroupId();

		treeNodeCacheModel.companyId = getCompanyId();

		treeNodeCacheModel.userId = getUserId();

		treeNodeCacheModel.userName = getUserName();

		String userName = treeNodeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			treeNodeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			treeNodeCacheModel.createDate = createDate.getTime();
		}
		else {
			treeNodeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			treeNodeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			treeNodeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		treeNodeCacheModel.value = getValue();

		treeNodeCacheModel.level = getLevel();

		treeNodeCacheModel.parentId = getParentId();

		treeNodeCacheModel.treeId = getTreeId();

		return treeNodeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", treeNodeId=");
		sb.append(getTreeNodeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", level=");
		sb.append(getLevel());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", treeId=");
		sb.append(getTreeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.nikhilesh.liferay.algorithm.model.TreeNode");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>treeNodeId</column-name><column-value><![CDATA[");
		sb.append(getTreeNodeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>level</column-name><column-value><![CDATA[");
		sb.append(getLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>treeId</column-name><column-value><![CDATA[");
		sb.append(getTreeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TreeNode.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TreeNode.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _treeNodeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _value;
	private int _level;
	private int _originalLevel;
	private boolean _setOriginalLevel;
	private long _parentId;
	private long _treeId;
	private long _originalTreeId;
	private boolean _setOriginalTreeId;
	private long _columnBitmask;
	private TreeNode _escapedModel;
}